### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Mister1Max1** [choffmann/MMM-Notion#2]
I don´t know if i got the right database id, but with the id i currently have in the config file every sixty seconds when the module updates itself it shows the error "TypeError: Cannot read properties of undefined (reading 'type')". If I use another database id it shows another error which says it cannot find a database with that id.

**Comment by Mister1Max1** [comment]
@choffmann it is the right id (i'm pretty sure about that)

**Comment by choffmann** [comment]
@Mister1Max1 Okay, i will take a look :eyes:

**Comment by Mister1Max1** [comment]
@choffmann idk how but I`ve managed to get it working. But it want to know if its possible to do not show tasks which are already checked (and if the anwser is yes with which code?)

**Comment by choffmann** [comment]
@Mister1Max1 Not at the moment. I am currently working on restructuring the project and adding new features. I will consider your idea
